global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ray_dashboard'
    static_configs:
      - targets: ['ray_dashboard:8266']
