# Usa a imagem oficial do Grafana como base
FROM grafana/grafana:latest

# Copia o arquivo grafana.ini da pasta local para o diretório de configuração do Grafana
COPY grafana.ini /etc/session_latest/metrics/grafana/grafana.ini

# YOLO_tools\ray_sessions\session_latest\metrics\grafana\grafana.ini